# frozen_string_literal: true

source 'https://rubygems.org' do
  gem 'coderay', '1.1.2' # will add colours to the rspec output
  gem 'nokogiri', '~> 1.10.8'
  gem 'pry'
  gem 'rspec', '~> 3.6'
  gem 'rspec-its'
  gem 'rubocop'
end
